// Generated by scripts/sync-version.mjs. Do not edit by hand.
export const AIMD_RELEASE = {
  "version": "1.0.1",
  "channel": "stable",
  "releaseUrl": "https://github.com/benjamin1108/aimd/releases",
  "updaterManifestUrl": "https://github.com/benjamin1108/aimd/releases/latest/download/latest.json",
  "updaterManifestAsset": "latest.json",
  "updaterSupportedPlatforms": [
    "darwin-aarch64",
    "windows-x86_64"
  ]
} as const;
