// Generated by scripts/sync-version.mjs. Do not edit by hand.
export const AIMD_RELEASE = {
  "version": "1.0.11",
  "channel": "stable",
  "releaseUrl": "https://github.com/benjamin1108/aimd/releases",
  "updaterManifestUrl": "https://github.com/benjamin1108/aimd/releases/latest/download/latest.json",
  "updaterManifestAsset": "latest.json",
  "updaterPubkey": "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDU2ODNBQzI3NUFCQTM1MjMKUldRak5icGFKNnlEVnFOVE9Vc2pXM3NScGEwREJiUVcvMGY1WU53ZUdIRlgyZ3hOTm90UTZFMlQK",
  "updaterSupportedPlatforms": [
    "darwin-aarch64",
    "windows-x86_64"
  ]
} as const;
